auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: forging2012/csi-attacher
  k8s.gcr.io/sig-storage/csi-provisioner: forging2012/csi-provisioner
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: forging2012/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-resizer: forging2012/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter: forging2012/csi-snapshotter



